apiVersion: v1
kind: Service
metadata:
  name: my-node-port-service
spec:
  selector:
    app: car_factory-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
      name: car-factory-app-test
  clusterIP: 10.96.0.2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-car-factory-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: car-factory-app
  template:
    metadata:
      labels:
        app: car-factory-app
    spec:
      containers:
      - name: my-container
        image: connorli0/car-factory-app:1.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      restartPolicy: Always
